### ISSUE TITLE
[BUG] OctoPrint 1.5.0 Tab Lists Missing

### ISSUE THREAD

**Issue by EddyMI3d** [jneilliii/OctoPrint-TabOrder#47]
In the Tab Order Settings, on some constellations, there are no entries below `Assigned Tabs` and `Hidden Tabs`
(Two installations work fine, one don't)
[Logs.zip](https://github.com/jneilliii/OctoPrint-TabOrder/files/5555773/Logs.zip)

![grafik](https://user-images.githubusercontent.com/8533327/99436256-8a83ac00-2911-11eb-9269-76d08bae1de9.png)

**Comment by jneilliii** [comment]
@EddyMI3d looks like your version of tab order is still not rc version. Copy/paste this link into plugin manager > get more > ...from URL and click install. After the upgrade it should work again.

```
https://github.com/jneilliii/OctoPrint-TabOrder/archive/0.5.12rc1.zip
```

**Comment by EddyMI3d** [comment]
According this, yes:

![grafik](https://user-images.githubusercontent.com/8533327/99442122-29f86d00-2919-11eb-9359-b9614cecc26d.png)

At the very end of the OctoPrint log, rc1 is listed.

But I'll try installing again.

**Comment by EddyMI3d** [comment]
Same result.

Do you need some data I can get via SSH?

**Comment by jneilliii** [comment]
Check config.yaml to see if there are any configured in the plugin's section. Also, check the developer console in the browser for any errors.

**Comment by EddyMI3d** [comment]
Ive got these entries in config.yaml

```
    taborder:
        _config_version: 5
        tabs:
        -   icon: fas fa-gamepad
            icon_color: '#00ffff'
            icon_tooltip: Control
            name: control
            showtext: false
            usetitle: true
        -   icon: fas fa-chart-line
            icon_color: '#ff0000'
            icon_tooltip: Temp
            name: temperature
            showtext: true
            usetitle: false
```
I've got no errors in the developer console.
